<a href="https://colab.research.google.com/github/last-war/HW_DataScience/blob/Homework-01/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

vect = np.array(np.arange(1, 11), dtype=int)
print(vect)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
import numpy as np

matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
import numpy as np

matrix = np.random.choice(np.arange(1, 11), size=(5, 5))

print(matrix)

[[ 1  4  8  8  3]
 [10  6  3  6  4]
 [ 5  8 10  3  1]
 [ 4  1 10  8  4]
 [ 3  2  8  1  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
import numpy as np

matrix = np.random.random((4, 4))
print(matrix)

[[0.78420492 0.20847391 0.09751149 0.40446884]
 [0.81512201 0.87320708 0.08358797 0.22790301]
 [0.07073748 0.08535871 0.08676688 0.26331227]
 [0.06472282 0.55474971 0.80358917 0.08027455]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(5))
matrix2 = np.random.choice(np.arange(1, 11), size=(5))
print(matrix1)
print(matrix2)
print('Addition')
mat_add = matrix1 + matrix2
print(mat_add)
print('Subtraction')
mat_sub = matrix1 - matrix2
print(mat_sub)
print('Multiplication')
mat_mul = matrix1 * matrix2
print(mat_mul)


[4 9 4 5 7]
[9 6 9 2 8]
Addition
[13 15 13  7 15]
Subtraction
[-5  3 -5  3 -1]
Multiplication
[36 54 36 10 56]



Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(7))
matrix2 = np.random.choice(np.arange(1, 11), size=(7))
print(matrix1)
print(matrix2)
mat_rez = np.dot(matrix1, matrix2)
print(mat_rez)

[1 9 7 3 6 3 5]
[9 9 4 3 2 3 2]
158



Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(2, 2))
matrix2 = np.random.choice(np.arange(1, 11), size=(2, 3))
print(matrix1)
print(matrix2)
mat_rez = np.dot(matrix1, matrix2)
print(mat_rez)

[[8 5]
 [5 4]]
[[5 6 3]
 [7 5 8]]
[[75 73 64]
 [53 50 47]]



Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [ ]:
import numpy as np

matrix = np.random.choice(np.arange(1, 11), size=(3, 3))
print(matrix)
mat_inv = np.linalg.inv(matrix)
print(mat_inv)

[[4 3 9]
 [2 2 7]
 [2 7 4]]
[[ 0.73214286 -0.91071429 -0.05357143]
 [-0.10714286  0.03571429  0.17857143]
 [-0.17857143  0.39285714 -0.03571429]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
import numpy as np

matrix = np.random.random((4, 4))
print(matrix)
t_matrix = matrix.T
print(t_matrix)

[[0.04537628 0.82982083 0.129354   0.98205929]
 [0.13181898 0.87047426 0.70412352 0.11102636]
 [0.732409   0.18382133 0.16784923 0.25484689]
 [0.9114776  0.22745097 0.05096559 0.24924184]]
[[0.04537628 0.13181898 0.732409   0.9114776 ]
 [0.82982083 0.87047426 0.18382133 0.22745097]
 [0.129354   0.70412352 0.16784923 0.05096559]
 [0.98205929 0.11102636 0.25484689 0.24924184]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(3, 4))
matrix2 = np.random.choice(np.arange(1, 11), size=(4))
print(matrix1)
print(matrix2)
mat_rez = np.dot(matrix1, matrix2)
print(mat_rez)

[[ 6  1  1 10]
 [ 6  9  7  8]
 [10  2  5  2]]
[5 4 8 8]
[122 186 114]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

matrix1 = np.random.random((2, 3))
matrix2 = np.random.random((3))
print(matrix1)
print(matrix2)
mat_rez = np.dot(matrix1, matrix2)
print(mat_rez)

[[0.39192166 0.8397205  0.00862815]
 [0.71213252 0.69323952 0.15776292]]
[0.72151729 0.85795083 0.46455731]
[1.00722542 1.18187126]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(2, 2))
matrix2 = np.random.choice(np.arange(1, 11), size=(2, 2))
print(matrix1)
print(matrix2)
mat_rez = matrix1 * matrix2
print(mat_rez)

[[2 4]
 [4 1]]
[[10  3]
 [ 3  9]]
[[20 12]
 [12  9]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(2, 2))
matrix2 = np.random.choice(np.arange(1, 11), size=(2, 2))
print(matrix1)
print(matrix2)
mat_rez = np.dot(matrix1, matrix2)
print(mat_rez)

[[6 8]
 [2 6]]
[[8 5]
 [2 6]]
[[64 78]
 [28 46]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
import numpy as np

matrix = np.random.choice(np.arange(1, 11), size=(5, 5))
print(matrix)
print(matrix.sum())

[[ 2  2  2 10  9]
 [10  4  4  2  8]
 [10  6  7  5  1]
 [ 3  1 10  9  8]
 [ 4  5  1  6  5]]
134


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
import numpy as np

matrix1 = np.random.choice(np.arange(1, 11), size=(4, 4))
matrix2 = np.random.choice(np.arange(1, 11), size=(4, 4))
print(matrix1)
print(matrix2)
mat_sub = np.subtract(matrix1, matrix2)
print(mat_sub)


[[ 6  1  4  4]
 [ 5  8  2  8]
 [ 6  2  8  2]
 [ 5  5 10  9]]
[[2 6 9 8]
 [7 3 5 8]
 [1 8 2 4]
 [4 5 1 2]]
[[ 4 -5 -5 -4]
 [-2  5 -3  0]
 [ 5 -6  6 -2]
 [ 1  0  9  7]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [57]:
import numpy as np

matrix = np.random.random((3, 3))
print(matrix)
rez = matrix.sum(axis=1).reshape(-1,1).T
print(rez)

[[0.15168351 0.40327594 0.67747201]
 [0.82138211 0.973896   0.40071794]
 [0.40265438 0.60843661 0.33702914]]
[[1.23243146 2.19599606 1.34812013]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
import numpy as np
matrix = np.random.choice(np.arange(1, 11), size=(3, 4))
#matrix = np.random.random((3, 4))
print(matrix)
rez = matrix * matrix
print(rez)

[[4 8 7 1]
 [4 5 1 6]
 [5 4 3 5]]
[[16 64 49  1]
 [16 25  1 36]
 [25 16  9 25]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
import numpy as np
matrix = np.random.choice(np.arange(1, 51), size=(4))
print(matrix)
rez = np.sqrt(matrix)
print(rez)

[23 10 16  8]
[4.79583152 3.16227766 4.         2.82842712]
