<a href="https://colab.research.google.com/github/last-war/HW_DataScience/blob/Homework-03/Hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing.csv')
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

напишіть функцію гіпотези лінійної регресії у векторному вигляді;

реалізуйте один крок градієнтного спуску;

In [12]:
class StudyLR:
    def __init__(self, lr: float = 0.01, thr: float = 0.0001, itr: int = 1000, count_w: int = 1):
        self.lr = lr
        self.thr = thr
        self.itr = itr
        self.w = np.array([x * 1. for x in range(count_w)])

    def predict(self, X: np.ndarray) -> list:
        return X @ self.w

    def update_w(self, X: np.array, y: np.array):
        self.w -= self.lr / len(y) * X.T @ (self.predict(X) - y)

    def fit(self, X: np.array, y: np.array):
        print(y)
        last_cost = 1000

        for i in range(self.itr):
            self.update_w(X, y)

            new_cost = cost(y, self.predict(X))
            if last_cost - new_cost < self.thr:
                print(i)
                print(f"w {self.w}")
                break
            last_cost = new_cost
        print(f"w {self.w}")

створіть функцію для обчислення функції втрат у векторному вигляді;

In [13]:
def cost(y: np.array, h: np.array) -> float:
    return np.mean((h - y) ** 2) / 2

знайдіть найкращі параметри ⃗ w   для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [14]:
X = df[['area', 'bathrooms', 'bedrooms']]
y = df['price']/1000000
X['area'] = X['area']/1000

linear_regression = StudyLR(count_w=X.shape[1], itr=1000)
linear_regression.fit(X, y)
print(linear_regression.w)


<ipython-input-14-471ae185b92c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['area'] = X['area']/1000


0      13.30000
1      12.25000
2      12.25000
3      12.21500
4      11.41000
         ...   
540     1.82000
541     1.76715
542     1.75000
543     1.75000
544     1.75000
Name: price, Length: 545, dtype: float64
314
w area         0.377248
bathrooms    0.908417
bedrooms     0.562263
dtype: float64
w area         0.377248
bathrooms    0.908417
bedrooms     0.562263
dtype: float64
area         0.377248
bathrooms    0.908417
bedrooms     0.562263
dtype: float64


знайдіть ці ж параметри за допомогою аналітичного рішення;

In [17]:
X = df[['area', 'bathrooms', 'bedrooms']][:3]
y = df['price'][:3]/1000000
X['area'] = X['area']/1000

X = np.array(X)
h = np.array(y)

X_inv = np.linalg.inv(X)

w = X_inv.dot(h)

w = X_inv @ h

print(w)


[ 0.63279302 -1.01225062  2.65729426]


порівняйте отримані результати.

In [5]:
X = df[['area', 'bathrooms', 'bedrooms']]
y = df['price']

regressor = LinearRegression().fit(X, y)
print(regressor.intercept_)
print(regressor.n_features_in_)
print(regressor.coef_)

scaler = MinMaxScaler()
nw_df = scaler.fit_transform(df.iloc[0:,0:4])
X = nw_df[0:,1:4]
y = nw_df[0:,0:1]
regressor_norm = LinearRegression().fit(X, y)
print(regressor_norm.intercept_)
print(regressor_norm.n_features_in_)
print(regressor_norm.coef_)


-173171.60763263796
3
[3.78762754e+02 1.38604950e+06 4.06820034e+05]
[0.0428274]
3
[[0.47714269 0.17611257 0.36001286]]
